language: node_js
node_js:
  - 11
script:
  # - npm run lint
  - npm test
  - make
deploy:
  - provider: npm
    skip_cleanup: true
    email: salomvary@gmail.com
    tag: latest
    on:
      repo: salomvary/multimedia-js
      tags: true
    api_key: $NPM_API_KEY
