language: node_js
node_js:
  - 11
script:
  - npm run lint
  - make
  # Would be nice to have this in before_deploy but it seems
  # to execute multiple times which does not work with npm version
  - if [ ! $TRAVIS_TAG ]; then npm version prerelease --no-git-tag-version --preid=build.$TRAVIS_BUILD_ID; fi
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: salomvary@gmail.com
    tag: next
    on:
      repo: salomvary/multimedia-js
      tags: false
    api_key: $NPM_API_KEY
  - provider: npm
    skip_cleanup: true
    email: salomvary@gmail.com
    tag: latest
    on:
      repo: salomvary/multimedia-js
      tags: true
    api_key: $NPM_API_KEY
